project:
  type: website
  output-dir: docs

website:
  title: "London Growth Cost Explorer"
  favicon: favicon.ico

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"